### ISSUE TITLE
Create Marketing Mad Lib 

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/webmaker-launch#1]
1- Create the different marketing Mad libs 
2 - Make them cool 

@hpauljohnson @secretrobotron

**Comment by lauradereynal** [comment]
Each Mad Lib will include a 
- Timeline 
- Budget 
- Team 
- Tactics 
- How you support the community 
- How do you want us to support you 
- Channels of communication

**Comment by secretrobotron** [comment]
Need to make sure goals are crisply stated:
- Content: 50 projects
- Community: ?? members
- Marketing: ?? eyeballs
- Overall: 10000 downloads and 5000 AUs

Can likely just pull these from the playbook.

**Comment by secretrobotron** [comment]
Started putting together an "overall" one here: https://etherpad.mozilla.org/webmaker-launch-campaign-template

**Comment by secretrobotron** [comment]
Need to drill into the templates for the roles.

**Comment by lauradereynal** [comment]
What are some ways that the activities are localized ? 

From Brian : @brianking
In india, provided 6 categories. 
Can you paste the india work here ? 
Can you look at the pad aboved ? 

@secretrobotron add SCRATCH things in the mad lib

**Comment by secretrobotron** [comment]
- Schedule: https://etherpad.mozilla.org/webmaker-launch-campaign-template
- Activity templates: https://docs.google.com/document/d/1jUUWLW0lw6JQXVWHcZ4KVonrunJxcYuR8rw0xUUZWDA/edit
- Activity sketch: https://docs.google.com/spreadsheets/d/1vDJJe0uaUX3pZQpycNLBd8QTA25N3f3F3s49iyHkeGE/edit#gid=1471748768

**Comment by secretrobotron** [comment]
ToDo: Put these in a wiki for easy access.

**Comment by lauradereynal** [comment]
Why?
Do you have a problem with etherpads?
:dance:

**Comment by secretrobotron** [comment]
:dancers:

**Comment by secretrobotron** [comment]
Do you mind adding feedback from BD, @LauraReynal? Provided it went well, we can add it to the wiki as an activity for other meetups.

**Comment by brianking** [comment]
Here is how we split things up last year in India for the Community Engagement sessions:
https://mozcampbeta.etherpad.mozilla.org/engagement-master

When it came to the actual Firefox OS launch, this plan was built out:
https://docs.google.com/presentation/d/1sI3T1vyPXZ6Wo4can-kncdpsHiSL9jahBF1USe3fLTI/edit?usp=sharing

Results (bus tour only):
https://docs.google.com/document/d/1W-NdkJmaZDLHABW1RA-g2BBlr14J3rN7BBI7USsJesE/edit?usp=sharing

Is this the type of thing you are looking for?

**Comment by secretrobotron** [comment]
:+1: I think so. Thanks, @brianking.

**Comment by lauradereynal** [comment]
Thanks 
@secretrobotron I will update after the meet up with data from BD.

**Comment by lauradereynal** [comment]
Meet-up happened - closing.
