### ISSUE TITLE
Finalize important dates

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-launch#10]
##### BD
- Kickoff: June 5-6
- Snippet: ____
- Launch: July 12
##### BR
- Kickoff: June 13
- Snippet: ____
- Launch: July 11 (FISL) and July 23-26 event (Campus Party)
##### KE
- Kickoff: June ___
- Snippet: ____
- Launch: July __
##### IDN
- Kickoff: June 13-16 (William is there)
- Snippet: ____
- Launch: August 11?
##### NA
- Kickoff: N/A
- Launch: Whistler
- Snippet: ____
- Get press publications for July 8

cc @HPaulJohnson

**Comment by secretrobotron** [comment]
Note: MozFestEA is July 17in Uganda: http://mozfestea.org/2015/

**Comment by secretrobotron** [comment]
How critical is it that someone is at each launch event?

**Comment by secretrobotron** [comment]
Ramadan is [June 18th to July 16th](http://en.wikipedia.org/wiki/Ramadan_%28calendar_month%29#Timing). Impacts KE, IDN, and BD.

**Comment by benrito** [comment]
Could impact positively—inquire with Natalia in Firefox org to understand how a Ramadan launch window could be advantageous

**Comment by lauradereynal** [comment]
@secretrobotron @HPaulJohnson I am closing this one since we are tracking in other calendars and these events have passed already.
