### ISSUE TITLE
Translate text to Bengali

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-launch#100]
We need a bit of text translated to Bengali.
#### Translation Needed

`Explore stories around the world ... or make your own!`
#### Design

Below is the design where the sentence of text will appear. We don't have that much space, so we need to use the most concise phrasing in Begali as possible.

![intro 1 copy 3 1x](https://cloud.githubusercontent.com/assets/1119821/9393328/556d5420-474f-11e5-93f0-5bbb626ecc1e.png)

**Comment by vazquez** [comment]
cc @secretrobotron

**Comment by bellayet** [comment]
Here is the translation,

Explore stories around the world ... or make your own!
আপনার চারপাশের দুনিয়ার গল্পগুলো আবিষ্কার করুন ... অথবা নিজেই তৈরী করুন!

**Comment by secretrobotron** [comment]
Thanks, @bellayet :D. Do you mind pinging another team member to review?

**Comment by vazquez** [comment]
How does it look @bellayet?

![intro bengali 1x](https://cloud.githubusercontent.com/assets/1119821/9413565/9ef91e74-4800-11e5-8f05-2b1649c95bf3.png)

**Comment by bellayet** [comment]
It looks good to me. 

I am adding @maktrix here to review the text.

**Comment by bolaram** [comment]
@secretrobotron  Hi, I am a Bangladeshi contributor . I review this . this text is right & looks great

**Comment by vazquez** [comment]
Thanks @bolaram!

**Comment by bolaram** [comment]
Welcome @vazquez
