### ISSUE TITLE
Translate text to Indonesian

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-launch#101]
We need a bit of text translated to Indonesian.
#### Translation Needed

`Explore stories around the world ... or make your own!`
#### Design

Below is the design where the sentence of text will appear. We don't have that much space, so we need to use the most concise phrasing in Indonesian as possible.

![intro 1 copy 3 1x](https://cloud.githubusercontent.com/assets/1119821/9393328/556d5420-474f-11e5-93f0-5bbb626ecc1e.png)

**Comment by vazquez** [comment]
cc @secretrobotron

**Comment by kelimuttu** [comment]
Temukan cerita dari seluruh dunia ... atau buatlah ceritamu sendiri!

**Comment by secretrobotron** [comment]
Thanks, @kelimuttu! Just to be clear,

"Explore stories from your world" = Temukan cerita dari seluruh dunia
"...or make your own" = atau buatlah ceritamu sendiri!

Right?

**Comment by vazquez** [comment]
How does it look @kelimuttu?

![intro indonesian 1x](https://cloud.githubusercontent.com/assets/1119821/9413578/ab20f0be-4800-11e5-877f-86ed29863790.png)

**Comment by kelimuttu** [comment]
That's right @secretrobotron 
Okay, great @vazquez!
