### ISSUE TITLE
Translate text to Brazilian Portuguese

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-launch#102]
We need a bit of text translated to Brazilian Portuguese.
#### Translation Needed

`Explore stories around the world ... or make your own!`
#### Design

Below is the design where the sentence of text will appear. We don't have that much space, so we need to use the most concise phrasing in Brazilian Portuguese as possible.

![intro 1 copy 3 1x](https://cloud.githubusercontent.com/assets/1119821/9393328/556d5420-474f-11e5-93f0-5bbb626ecc1e.png)

**Comment by vazquez** [comment]
cc @secretrobotron

**Comment by rodrigowaters** [comment]
@vazquez 

Explore histórias ao redor do mundo ... ou faça a sua !

**Comment by secretrobotron** [comment]
Thanks @rodrigowaters :D.

Do you mind pinging another team member to review?

**Comment by vazquez** [comment]
How does it look @rodrigowaters?

![intro brazilian portuguese 1x](https://cloud.githubusercontent.com/assets/1119821/9413582/b3f0f428-4800-11e5-96e0-9a1de4fcbb2b.png)

**Comment by cpswsg** [comment]
@vazquez  where's:
"sua !" substitute by "sua!"
"Eu entendo" substitute by "Entendi"

@IanRamosC, could you review, please?

**Comment by IanRamosC** [comment]
@vazquez I think you just need to apply the changes made by @cynthiapereira and it's okay. :smile:

**Comment by vazquez** [comment]
Done! Thanks everyone!
