### ISSUE TITLE
Choose a category for Play store

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-launch#17]
Question came up today in conversation with @HPaulJohnson. Have we picked one? We will list under Social? Or a less competitive category? Does google provide analytics on [these categories](https://support.google.com/googleplay/android-developer/answer/113475) and their audiences? 

cc @thisandagain

**Comment by thisandagain** [comment]
Good question. They don't, but [App Annie](https://www.appannie.com) and a few other services do. Social is _incredibly_ competitive FWIW ... we may want to look at "Tools".

**Comment by xmatthewx** [comment]
Looks like you can change the category later with some latency. Here's a shorter list of options: 

Social
Tools
Productivity
Lifestyle
Entertainment
Education
Communications

**Comment by HPaulJohnson** [comment]
I have a few friends over at App Annie so I have a question into them about any intelligence around this that could help us make a decision. I'll have a better update shortly.

**Comment by secretrobotron** [comment]
@xmatthewx @thisandagain we can close this now, right?

**Comment by xmatthewx** [comment]
Yes. Category chosen. Probably worth testing alternatives after we establish a baseline.
