### ISSUE TITLE
Make a wiki to track links

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/webmaker-launch#2]
Goal: 
Have a _clean_ space for tracking different work. 

Reason: This google doc is too noisy for broad participation https://docs.google.com/document/d/1hnpXwboPWv_VLa_NiKHYDnWyIB9IjEc89adoKgOuvPY/edit#
@secretrobotron 

---

Model
This is what we did - this is the link

**Comment by secretrobotron** [comment]
Done https://github.com/mozilla/webmaker-launch/wiki

Added a couple different pages to categorize stuff.
