### ISSUE TITLE
Bangladesh GTM - Curriculum test

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/webmaker-launch#22]
Team : @jaggedzak @asif21 @smamir-tuhin @srdesh @Amena-Islam @gauthraj 

Goal : Test 3 units of curriculum during the week of the 8th -12th and improve the curriculum for Bangladesh

Pad : https://bd.etherpad.mozilla.org/curriculum

**Comment by lauradereynal** [comment]
Draft curriculum waiting for an update by monday https://docs.google.com/document/d/1InFeyRmkFNWVWuimD1Ayu6tRMUr7ZgE7eJx0nkL0uGk/edit?usp=sharing

**Comment by srdesh** [comment]
Team timing https://docs.google.com/document/d/1ZQQxXaiC1x47Ho1alum9zd9U8GF-OWJUPUEeXUVsA4g/edit?usp=sharing

**Comment by lauradereynal** [comment]
I added comments on the pad - line 108 - things to figure out by the end of the day ? 
Also, feel free to invite more Mozillians for these 3 testing sessions. 
:dancers:

**Comment by lauradereynal** [comment]
The first round of curriculum has been tested and report has been submitted. Thanks to you all team :smile: will ping when there is something new
