### ISSUE TITLE
Bangladesh GTM - Celebrities endorsement 

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/webmaker-launch#26]
Team : @SOFTtowaha 
Goal : Get 2 celebrities endorsement for Webmaker

**Comment by SOFTowaha** [comment]
Planning pad: https://bd.etherpad.mozilla.org/celebrities

**Comment by HPaulJohnson** [comment]
@SOFTowaha Thanks for this. I left a few questions and comments in the pad. 

I think the next, best step might be to create a list of the most influential people on social media that we might want to reach out to. They don't have to be celebrities but should have lots of followers. 

Overall, I think this should be part of a bigger social media strategy which we are tracking over here https://github.com/mozilla/webmaker-launch/issues/37

Let's consolidate and start tracking everything over there in that issue.

**Comment by lauradereynal** [comment]
@SOFTowaha I agree with @HPaulJohnson that we should work with the social media team. Im closing this issue then, and adding you to the other one.
