### ISSUE TITLE
Document localization process

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/webmaker-launch#28]
Proposition :  Meet with localization team in BD in order to understand the following questions. 

cc / @secretrobotron do you have a list of questions / desires for this activity ? 
1. What is difficult / what is easy ?
2. How could we improve the process / make it easier for you ?
3. Which is your preferred software and why ? 
4. Can we do a screen cast of the experience ?

**Comment by secretrobotron** [comment]
I'd say number 4 would be excellent, especially if it can be done with Webmaker (which should work soon, but not yet).

Maybe, also,
- How much do you rely on communities of localizers, like Transifex?
- Have you had any localization experience in the past?
- Can you describe the best way to work with a team of developers and designers?
  - What is the preferred frequency for string updates?

**Comment by lauradereynal** [comment]
@secretrobotron @alicoding 
cc/ FYI @thisandagain @geroter

Had a discussion with the 3 leaders for the localization efforts in BD. I wrote the answers in this document to facilitate comments / questions : https://docs.google.com/document/d/1x2_sk2sPJ5XGhj-6hfSR9MTOIAHG8xPa34Z_YfyUjjc/edit?usp=sharing

Let us know if we need more, I'm sure @jaggedzak @bellayet @maktrix  can also provide details. 
Thanks :earth_asia: :earth_africa: :earth_americas:

**Comment by lauradereynal** [comment]
Closing this for now, until we have more localization questions ! Thanks team

**Comment by secretrobotron** [comment]
cc @simonwex
