### ISSUE TITLE
Refine GTM strategy & playboook 

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/webmaker-launch#29]
Goal: Given observations from Bangladesh, refine the playbook and the way we approach GTM with the community.

Team: @secretrobotron @HPaulJohnson

**Comment by lauradereynal** [comment]
Paul added slide about Webmaker 's transition  :white_check_mark: 
Next, I propose to remove the last part of "perks of being a Webmaker volunteer" and to deal with honorariums on a per-country need assessment. 
@HPaulJohnson any thoughts ?

**Comment by HPaulJohnson** [comment]
works for me. (deleted "honorariums" from perks section.)

**Comment by lauradereynal** [comment]
Closing this, it seems like we are good with the playbook
