### ISSUE TITLE
Find out what info printers need in regions to make assets

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-launch#30]
- Do they have templates we need to fill out?
- What things can't they print?

**Comment by secretrobotron** [comment]
Related to #8.

**Comment by lauradereynal** [comment]
I think the 3 colors of Bangladesh, Brazil and Indonesia go very well together. It's a nice rainbow 
:rainbow:

**Comment by secretrobotron** [comment]
This is well underway in another channel.
