### ISSUE TITLE
Prepare for Whistler Science Fair

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-launch#31]
- [ ] Prepare demo slides (can come from Intro deck)
- [ ] get a few Nexus 5s
  - @secretrobotron x 1
  - @k88hudson x 3
- [ ] put Webmaker on them

**Comment by secretrobotron** [comment]
Basics from @thisandagain 

> • Booth with display that has our intro slides on loop giving a general overview of the application
> • Bunch of Nexus 5’s running latest Webmaker release build
> • Prompts for getting started making / sharing a project
> • At least 2 people covering the booth

**Comment by secretrobotron** [comment]
Signed up @adamlofting and @k88hudson to help :).

**Comment by k88hudson** [comment]
Note, I have nexus 4s, not 5s

**Comment by secretrobotron** [comment]
@k88hudson :+1: should be fine

@thisandagain do you have a phone you can spare too?

**Comment by lauradereynal** [comment]
:shipit:

**Comment by lauradereynal** [comment]
Should we have lower quality phones too ? 
Im bringing back 2 commonly purchased phones from Bangla 
and @thisandagain and @k88hudson each have a micromax from India.

**Comment by secretrobotron** [comment]
@LauraReynal :+1: those will be cool for people to try out. I'll track down @k88hudson for the micromax.

**Comment by thisandagain** [comment]
Sure! I've got a Nexus 4 I will bring and a _ton_ of lower-end and older Android devices.

**Comment by lauradereynal** [comment]
Me too I now have 4 phones from Bangladesh from 45 - 100 USD
