### ISSUE TITLE
Design Printed Assets for Webmaker Launch

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker-launch#33]
Driver: @edrushka
Design lead: @lovegushwa 
QA: @cassiemc
Print production coordinator: TBD (possibly Jordan)
CC: @secretrobotron @HPaulJohnson

We need the following designed, to be printed, for the Webmaker Launch in July
#### P1 Must Haves
- [ ] Posters : https://github.com/mozilla/webmaker-launch/issues/53
- [ ] Stickers
- [x] Buttons
#### P2 Nice to Haves
- [ ] Shirts
- [ ] Postcards
#### Deadlines for assets to be on the ground
- June 22: English stickers in Whistler
- July 5: Bangla assets 
- July 12: Indonesian and Brazilian Portuguese assets 
- July 18: English assets in Kenya  

Progress charted [here](https://docs.google.com/spreadsheets/d/1zD_pVMKIpjPR_LicXIBb-zbA1ts_L1b03MB2iszvlXE/edit#gid=396925387).

**Comment by lovegushwa** [comment]
R? @cassiemc @HPaulJohnson @edrushka
My vote is the one that is less likely to show up at goodwill, and if it did show up at good will I would buy it. 

![screen shot 2015-06-16 at 5 44 26 pm](https://cloud.githubusercontent.com/assets/12228435/8197630/5e04b4f8-144f-11e5-8896-9867e3a1f64b.png)

![screen shot 2015-06-16 at 5 32 15 pm](https://cloud.githubusercontent.com/assets/12228435/8197593/de6b9428-144e-11e5-8cde-20bfbdffd267.png)

**Comment by HPaulJohnson** [comment]
+1 on the first one (assume we agree that it would be the least likely to show up at Goodwill)

**Comment by cassiemc** [comment]
Yeah I like the first one better but wonder if it's slightly awkward for women. Maybe making it a bit smaller would fix? @lovegushwa @HPaulJohnson

**Comment by lovegushwa** [comment]
Good call @cassiemc  maybe we can do a larger and smaller size. Can find out tomorrow.

**Comment by cassiemc** [comment]
It'd be a good idea. http://geekfeminism.wikia.com/wiki/T-shirts

**Comment by mijanurrahman** [comment]
+1 for the first Tshirt. What ll have on back side? @lovegushwa

**Comment by edrushka** [comment]
I'd prefer to do one design for this run. It's only 100 shirts, so we can improve the design when we print the next batch.

**Comment by edrushka** [comment]
@mijanurrahman there's nothing on the back side.

**Comment by edrushka** [comment]
@HPaulJohnson @cassiemc confirming you've given R+ to this [final sticker design](https://drive.google.com/drive/folders/0B4rEOP1A0tc0fklGMS15Vk41UG1rRllpTkFhdHBOajhXdk90YXFEb09aMGZpajRSU0NtXzg/0B4rEOP1A0tc0flFZXy0yWnFFcGtNUTQwblNfNjNUSC1TRnR0eDNXam5NNEQxak4zRkZlcms) before we send to print.

**Comment by cassiemc** [comment]
@edrushka R+ on the sticker. We should see after this batch if we want to adjust with a heavier text weight.

Re. t-shirts, will there be multiple sizes, ladies and mens? I would prioritize a smaller logo for ladies if we can only have one implementation.

**Comment by edrushka** [comment]
There will be multiple sizes (XS, S, M, L, XL) hopefully with some of the smaller sizes in 'fitted'.

**Comment by lovegushwa** [comment]
Hi All, Here is an adjusted version. @cassiemc @HPaulJohnson  @edrushka 
![screen shot 2015-06-17 at 10 13 00 am](https://cloud.githubusercontent.com/assets/12228435/8213806/7e3c6ccc-14d9-11e5-957f-dad88de77d3f.png)

**Comment by edrushka** [comment]
cc @jaykappa

**Comment by cassiemc** [comment]
@lovegushwa Can you put it on a female model? I suspect it needs to be smaller yet and perhaps higher on the t-shirt.

**Comment by lovegushwa** [comment]
@cassiemc R?
@HPaulJohnson @edrushka 

I revised the imprint size. We can also go with more of a badge version. Let me know if were are in the ballpark. 

![screen shot 2015-06-17 at 4 26 40 pm](https://cloud.githubusercontent.com/assets/12228435/8221212/528fc13c-1510-11e5-9565-b0306b89d389.png)
![screen shot 2015-06-17 at 4 49 53 pm](https://cloud.githubusercontent.com/assets/12228435/8221259/1aa15712-1511-11e5-81aa-52eb6ef3f293.png)

![screen shot 2015-06-17 at 4 22 42 pm](https://cloud.githubusercontent.com/assets/12228435/8221215/57cdc428-1510-11e5-803a-98a873bc38f1.png)

**Comment by edrushka** [comment]
Awesome, Jordan! I prefer the larger one because I like the logo but I'll leave it to  Paul to decide and Cassie to sign off.

**Comment by cassiemc** [comment]
R+ both of these. I do like that badge, but the big one feels more like it hits the marketing needs better. Thanks for the persistence @lovegushwa :)

**Comment by edrushka** [comment]
@HPaulJohnson it's your call!

**Comment by HPaulJohnson** [comment]
Larger one is great. Save me one :)

**Comment by lovegushwa** [comment]
Cool @cassiemc @HPaulJohnson @edrushka  I'll get the artwork ready!

**Comment by lovegushwa** [comment]
@edrushka 

The final layered CS5 AI file is on the drive. Also we should send over the two latest Women's, Men's comps. (all these files are in Webmaker-t-shirt-artwork.zip). The .AI should be really close to the correct size but the printer should compare with the comps and send a digital proof of the imposition. I'm sure they are pro's.
![screen shot 2015-06-17 at 9 41 59 pm](https://cloud.githubusercontent.com/assets/12228435/8224305/cc5521e6-1539-11e5-9237-1042df14a46e.png)
