### ISSUE TITLE
Create a set of marketing messages that I could test in Bangladesh 

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/webmaker-launch#36]
@HPaulJohnson would you be able to create ~5 marketing messages that we could test in real life here ? 
Example : 
- Share the things you love 
  vs 
- Make the web in Bangla 
  ... 
  we could see what resonates most with our audience

**Comment by HPaulJohnson** [comment]
@LauraReynal yes! working on a key messaging doc today so that should get you started. I'm hoping by early next week we can also provide some ealry mockups of actual ads for you to get some quick feedback on.

**Comment by lauradereynal** [comment]
Ping @edrushka this bug is related to your question from earlier email

**Comment by HPaulJohnson** [comment]
@LauraReynal we likely won't have any of the more fully developed creative assets until later in the week. Is the key message doc that I sent last week sufficient? Otherwise, we can mock up some additional headlines/ads just so you can get feedback while you are there.

**Comment by lauradereynal** [comment]
the messages are already great to test, 
the one with creativity is the winner 
Sharing is in second position. 

I have little time left here, so anything else to test, please send today :fire: 

@edrushka @HPaulJohnson
