### ISSUE TITLE
Edit shortlink to point to playstore

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker-launch#39]
Assigned to @kevzawacki

When the app is available for download, edit the mzl.la shortlink to point directly to the Play Store.

It's currently: https://beta.webmaker.org/#/
Edit to point to: https://play.google.com/store/apps/details?id=org.mozilla.webmaker

cc @HPaulJohnson @secretrobotron @thisandagain

**Comment by HPaulJohnson** [comment]
I think we'll need country specific short-links for localized marketing assets. For now they can all point to the same play.google.com link and as locale-specific instances of the app show up we can update the links. Make sense?

**Comment by KevZawacki** [comment]
Sounds good

**Comment by KevZawacki** [comment]
The http://mzl.la/webmaker shortlink now redirects to the Google Play Store. Give it a try -- let me know if you experience any issues.

**Comment by secretrobotron** [comment]
:+1: looks good!

**Comment by edrushka** [comment]
:star2: Thanks Kevin!

**Comment by edrushka** [comment]
@lovegushwa here's the shortlink
