### ISSUE TITLE
Bangladesh GTM - Figure out how to provide resources

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/webmaker-launch#40]
_Goal_: Community members are going to host workshops / events / do stuff 

_Action_: need to have a clear budget for supporting these different actions and a process to implement it. 
It's becoming quite urgent since people are ready to start and already asking for details. 
- [x]  Decide how much we allow 
- [ ]  Write up or copy a set of guidelines ( I have seen some heavy requests - these are needed ) 
- [x]  Figure out process  - Should we go through a Reps program? Through a PM in Bangladesh? Else?

Thoughts? 

Driver: needs driver
Team : @secretrobotron @HPaulJohnson @davidascher 
Consulted : @brianking @rosanardila

**Comment by davidascher** [comment]
Sounds like the reps program might be a good way to do it if it works for
Pamela. Has @secretrobotron or @hpauljohnson talked to her yet?

If someone puts forth a budget plan I'm happy to review it.

**Comment by lauradereynal** [comment]
Thanks @davidascher 

I made a buget here with @jaggedzak based on the cost we encountered in Dhaka. 
It will come to 35 USD without location rent or 55 USD with renting a cheap place we used. 

@secretrobotron @HPaulJohnson do we have a bigger budget existing already somewhere ?

**Comment by rosanardila** [comment]
we can certainly use the Reps program to get the money to the field. 
We can probably also fund some initiatives. Let us know if you have a budget so that we can make things go smoothly.

**Comment by secretrobotron** [comment]
@HPaulJohnson is creating a budget we can follow. Stay tuned.

We'll use the reps program if we can. It's great.

**Comment by lauradereynal** [comment]
This is undercontrol and WIP by @secretrobotron and @HPaulJohnson . Closing
