### ISSUE TITLE
Print assets for launch

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker-launch#42]
Driver: @edrushka
Designer: @lovegushwa
Signoff: @HPaulJohnson 
CC'd: @secretrobotron @benrito @LauraReynal 

[Here are the assets we're printing](https://docs.google.com/spreadsheets/d/1zD_pVMKIpjPR_LicXIBb-zbA1ts_L1b03MB2iszvlXE/edit#gid=396925387). Jordan, please add the print specs and we'll update this ticket with quotes as they come in.

**Comment by lovegushwa** [comment]
Hi All, You can pull up the print specifications in this etherpad:
https://etherpad.mozilla.org/JopE4UtXDi

I'm working on one quote in Portland but need to bring in a few more if possible.

**Comment by edrushka** [comment]
Update: we're  hiring a contractor to oversee the actual printing and shipping. A few quotes collected already.

**Comment by cassiemc** [comment]
@lovegushwa @edrushka  StickerYou is a company in Toronto that'll print stickers online. http://www.stickeryou.com/

**Comment by rodrigowaters** [comment]
When will be sent to Brazil?

**Comment by secretrobotron** [comment]
@rodrigowaters we're working on dates right now!

**Comment by secretrobotron** [comment]
@rodrigowaters see https://github.com/mozilla/webmaker-launch/wiki/Swag

Will keep it updated with more info as it comes in.

**Comment by rodrigowaters** [comment]
@secretrobotron Send in July 17? The event will be July 12 ( Brazil )
