### ISSUE TITLE
Create digital assets kit for partners

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker-launch#43]
Driver @edrushka
Copy @kevzawacki
Design: @jaykappa
QA: @cassiemc & @lovegushwa 
Signoff @HPaulJohnson 

Need to create content for a digital partners kit. [This one from Maker Party](https://docs.google.com/document/d/1O7BJf63vPjNLLV8GWXB_xs2ZF7IdPnAMm4uktEGKHMc/edit) is a good template.

We need partner-facing
- [ ] Intro on how to use the kit
- [ ] Sample blog post
- [ ] Sample social media

@kevzawacki, can you draft and we'll give to Jay to package?

**Comment by KevZawacki** [comment]
Sure, I'm on it!

**Comment by edrushka** [comment]
@HPaulJohnson This should be translated, no?

**Comment by KevZawacki** [comment]
The Webmaker Partners Kit is ready for review: https://goo.gl/SL4JMY
Drop in any and all additions and revisions!

**Comment by HPaulJohnson** [comment]
Nice @KevZawacki - I added a few comments/suggestions but this is very close. Going to get input from @cecilepompei tomorrow for a partnership/BD perspective. 

With that input I think we can finalize (and once we get the resources in the dropbox of course). Would be nice if the final asset here was a well-designed PDF.

**Comment by KevZawacki** [comment]
Thanks, @HPaulJohnson -- I've just updated the doc per your suggestions.

**Comment by edrushka** [comment]
@jaykappa is also going to do some research to see if there are other good examples of this, and if there are other assets we should be including.

**Comment by jaykappa** [comment]
**Redpen URL:**
https://redpen.io/p/vnd5a95dd70f79a748

I tried to find some good examples but nothing caught my attention to what I think would might work here. So decided to simply progress with layout for review. The cover should most likely be adjusted once final print assets are selected.

**Notes**
Each section has its own page in anticipation of additional incoming copy, as well as the unknown length of translated copy.

Some elements borrow from previous digital assets (i.e. using the Download button as a backdrop for individual sample social media messages) to tie-in/reinforce the look that we've established so far across the board (pending review still).

R? @cassiemc @edrushka @lovegushwa

**Comment by edrushka** [comment]
@jaykappa - this is a great start. First impression is that it seems like a lot of text. Would it work to include some creative assets into the doc, without linking away (e.g. web banners, logos) or will the quality be too low embedded in a PDF? 

Another idea to break up the "great wall of text" would be to include some of the screenshots and/or PlayStore graphics.

Adding @KevZawacki to provide feedback as well.

**Comment by jaykappa** [comment]
@edrushka it would be great to add some creative assets to help make each page a bit more visually appealing. If hi-res screenshots can be provided I can throw them in. Currently I only have one asset (the phone with the app screenshot) but could use a few more. 

The Playstore graphics are great but I could benefit with having CS6 artwork files to use (if possible please).

**Comment by edrushka** [comment]
@vasquez Do you have the Playstore artwork files in CS6 for @jaykappa?

**Comment by cassiemc** [comment]
@vazquez (note spelling @edrushka with a 'z' not 's') is on PTO today and tomorrow. Cc'ing @lovegushwa to see if he can provide more assets and feedback as well. 

I like how clean this looks, the text is set nicely. Agree more visual interest would help. If the final result is a pdf, seems important from usability pov that the text is selectable and that the final file size is not too big (would say around a couple mbs but not sure that applies to all our partner's contexts ). @HPaulJohnson thoughts on target file size?

@jaykappa could you link to an actual pdf here so I can try out a more realistic browsing experience? Redpen is good for some things but not really that!

You could break up the blue background pages with a couple of pages with white background, or at least a white background in the main content area – probably on the pages with the sample writing to make that particular content feel a little more white label (blog, email, social media) / reusable in many different contexts. 

The pages could also easily be multiple color background fields, drawing from the wm palette.

@jaykappa Have you looked at the research reports? 
    India: www.mzl.la/india
    Kenya: www.mzl.la/kenya
    Bangladesh: www.mzl.la/bangladesh

@lovegushwa can you also link to the latest Chicago report so we can show Jay how the design of these is evolving. Thanks!

**Comment by jaykappa** [comment]
@cassiemc here's a link to the PDF view:
https://dl.dropboxusercontent.com/u/3603970/2015-Webmaker-PartnerKit-Eng-V1.pdf

**Comment by cassiemc** [comment]
Cool thanks @jaykappa!

**Comment by KevZawacki** [comment]
Peppering screenshots throughout the report would be great! & @jaykappa, I've added a couple comments to the Red Pen.

@HPaulJohnson is on PTO, so I'll weigh in on file size in his absence. Our research reports are about ~6.5MB apiece. Can we shoot for < that?

**Comment by vazquez** [comment]
Perhaps alternating between the blue and the purple (we call it plum) would
make for a nice visual pattern. The purple also looks great with white text
on top of it. Give that a shot :)

On Monday, June 29, 2015, Kevin Zawacki notifications@github.com wrote:

> Peppering screenshots throughout the report would be great! & @jaykappa
> https://github.com/jaykappa, I've added a couple comments to the Red
> Pen.
> 
> @HPaulJohnson https://github.com/HPaulJohnson is on PTO, so I'll weigh
> in on file size in his absence. Our research reports are about ~6.5MB
> apiece. Can we shoot for < that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/webmaker-launch/issues/43#issuecomment-116737311
> .

## 

Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez http://twitter.com/iamrvazquez
IRC: ricardo

**Comment by cassiemc** [comment]
@jaykappa: you can find plum and it’s evil twin shadow plum here: https://github.com/mozilla/webmaker-android/search?utf8=%E2%9C%93&q=plum

**Comment by edrushka** [comment]
Quick update: Bobby and I have terrible wifi in Scotland so he's not even going to attempt localizing this doc until next week. In the meantime, let's get the design of the English version finalized.

**Comment by jaykappa** [comment]
I've updated the Kit based on feedback for R? @cassiemc @lovegushwa @edrushka 
https://dl.dropboxusercontent.com/u/3603970/2015-Webmaker-PartnerKit-Eng-V5.pdf

Just would need images to swap out with for localization.

**Comment by edrushka** [comment]
This is looking really good! I'll let @cassiemc and @lovegushwa continue to manage the design feedback, but just wanted to give a general YAY :tada: for this direction.

**Comment by cassiemc** [comment]
- The initial webmaker logo on p1 feels way to big. It's also lacking a gradient so I am wondering if the correct version is placed or of something happened to it in downsampling the images in the file? Overall would prefer more whitespace around the logo, so that it feels more elegant and refined; less in-your-face. 
- Really love the new layouts! And alternating between full color, color with white borders and full white is working _really_ well. My only tweak here might be to style the 'sample email' page in the same way as the twitter and facebook pages, possibly using an envelope icon, with the white border around the page and perhaps a background behind the email content.
- Should still create custom shortlinks for the dropbox and flickr links. cc @KevZawacki  
- Next step: finalize the images for each page
- thank you page?

**Comment by KevZawacki** [comment]
@cassiemc Good call. In the interest of our potential partners not having to squint at screens and mistake Is for 1s, here are customized shortlinks:

http://mzl.la/WebmakerAssets (for the Dropbox link)
http://mzl.la/WebmakerPhotos (for the Flickr link)

Note: These links are case sensitive. Probably worthwhile to note that in the kit.

**Comment by jaykappa** [comment]
An updated view of the partners kit with major changes to the cover + fixes to the pages mentioned.
https://dl.dropboxusercontent.com/u/3603970/2015-Webmaker-PartnerKit-Eng-V8-Spreads.pdf

R? @cassiemc

**Comment by cassiemc** [comment]
Great work @jaykappa, loving the updates! I like the new structure and looks to me like the final changes will be to really hone in on the right photo choices. 

@KevZawacki Can you provide input on the final page, the thank you, and maybe some copy there if you like it (perhaps some contact info)? We thought it would make a nice bookend to the package. Alternatively I think we could scrap the copy on that page and just have a nicely centered thank you + logo.

**Comment by edrushka** [comment]
Gorgeous! This is really coming along!! @HPaulJohnson will be back next week to give final signoff on this. Thanks so much for your work on this @jaykappa @KevZawacki @cassiemc

**Comment by jaykappa** [comment]
With some incredible image selections from @lovegushwa the Partners Kit has been updated for Review:

https://dl.dropboxusercontent.com/u/3603970/2015-Webmaker-PartnerKit-Eng-V9-Spreads.pdf

@cassiemc @edrushka @HPaulJohnson

**Comment by jaykappa** [comment]
The kit has been updated with the new screens as suggested. 

**PDF Download:**
https://dl.dropboxusercontent.com/u/3603970/2015-Webmaker-PartnerKit-Eng-V10-Spreads.pdf

**Screenshots**
![2015-webmaker-partnerkit-eng-v10](https://cloud.githubusercontent.com/assets/1036635/8602947/231c2834-2643-11e5-90b9-39f1131a8c61.jpg)
![2015-webmaker-partnerkit-eng-v102](https://cloud.githubusercontent.com/assets/1036635/8602953/26b74208-2643-11e5-80aa-d556bb446456.jpg)
![2015-webmaker-partnerkit-eng-v103](https://cloud.githubusercontent.com/assets/1036635/8602958/2a0f5f8a-2643-11e5-8e3a-0c4a8d3915e6.jpg)
![2015-webmaker-partnerkit-eng-v104](https://cloud.githubusercontent.com/assets/1036635/8602966/3044e5e6-2643-11e5-88db-4e2adf35492e.jpg)
![2015-webmaker-partnerkit-eng-v105](https://cloud.githubusercontent.com/assets/1036635/8602964/303338aa-2643-11e5-97d7-6da8949b4451.jpg)
![2015-webmaker-partnerkit-eng-v106](https://cloud.githubusercontent.com/assets/1036635/8602967/3045766e-2643-11e5-8d9d-13bfdf00860a.jpg)
![2015-webmaker-partnerkit-eng-v107](https://cloud.githubusercontent.com/assets/1036635/8602968/30469c06-2643-11e5-8990-c3ed94f8578e.jpg)
![2015-webmaker-partnerkit-eng-v108](https://cloud.githubusercontent.com/assets/1036635/8602969/30486310-2643-11e5-998f-7a206088a879.jpg)
![2015-webmaker-partnerkit-eng-v109](https://cloud.githubusercontent.com/assets/1036635/8602965/304219ec-2643-11e5-9750-f26aff6483a0.jpg)

**Comment by HPaulJohnson** [comment]
Final changes: 
- Change title from "Partner Kit" to "Promotional Kit"
- On page 13, remove "Preload Webmaker on your devices"

**Comment by jaykappa** [comment]
@HPaulJohnson @edrushka @cassiemc I've updated the source file and PDF's on Google Drive with the two changes noted.
