### ISSUE TITLE
Design poster

### ISSUE THREAD

**Issue by cassiemc** [mozilla/webmaker-launch#53]
Filing this as a new issue to document and share iterations.

**Comment by cassiemc** [comment]
Here's a hand. What do you think @lovegushwa? I'm going to put the final assets in Drive / Launch Assets / Process / Hand. I don't have much more time to put into this today so if you need to pull it down and make any adjustments yourself, please do!
![hand-v5-13](https://cloud.githubusercontent.com/assets/1186326/8213185/2ebd62ea-14ee-11e5-9bee-44b55210f424.png)

**Comment by lovegushwa** [comment]
@cassiemc Looking great thank you!!

**Comment by edrushka** [comment]
@HPaulJohnson - we need to finalize copy on this before end of day Friday (Eastern) so Cassie can sign off and we can hand over to Karen.

**Comment by edrushka** [comment]
cc @jaykappa

**Comment by edrushka** [comment]
@HPaulJohnson updating that deadline as cassie will be PTO beginning tomorrow afternoon. Can we get the finalized copy by EOD today? cc @kevzawacki

**Comment by HPaulJohnson** [comment]
This design is looking good. Per our conversation last night, now that we have a design, I'd love to see a few different variations of messages in this layout and then do a lightening round of feedback from a slightly wider audience before we finalize and localize. 

Here are the copy variations I sent around last night: https://etherpad.mozilla.org/webmaker-launch-poster

Is it possible to do some mockups with this design and at least some of these versions?

**Comment by edrushka** [comment]
Awesome @HPaulJohnson! Let's finalize this pad by EOD and ask @lovegushwa to mock up the best variations.

**Comment by HPaulJohnson** [comment]
Let's consider the pad final so we can keep moving. @lovegushwa feel free to mock up now.

**Comment by lovegushwa** [comment]
@HPaulJohnson @edrushka  ... out sticker hunting, will send variations shortly.

**Comment by cassiemc** [comment]
@lovegushwa a note – The purple shadow might be too dominant, it kinda "overshadows" the logo+copy at the bottom, ha-ha.

**Comment by lovegushwa** [comment]
@HPaulJohnson @cassiemc @edrushka 

Hi all, copy options posted, Also a PDF file is up on the drive. 
Webmaker Launch Assets > 16 Posters - Medium (Jordan) > Webmaker-18x26-copy-options.pdf

![webmaker-18x26-01](https://cloud.githubusercontent.com/assets/12228435/8220805/0de3896e-150c-11e5-8fa6-6e3728cae3c0.jpg)
1

![webmaker-18x26-02](https://cloud.githubusercontent.com/assets/12228435/8220806/0de463d4-150c-11e5-8425-688bb2dd1b09.jpg)
2

![webmaker-18x26-03](https://cloud.githubusercontent.com/assets/12228435/8220804/0de2b994-150c-11e5-9d0d-03be7315276f.jpg)
3

![webmaker-18x26-04](https://cloud.githubusercontent.com/assets/12228435/8220809/0de5f276-150c-11e5-9366-4605d5bed85c.jpg)
4

![webmaker-18x26-05](https://cloud.githubusercontent.com/assets/12228435/8220808/0de56d2e-150c-11e5-8961-44898ce2099b.jpg)
5

![webmaker-18x26-06](https://cloud.githubusercontent.com/assets/12228435/8220807/0de50636-150c-11e5-8034-36156a8906f6.jpg)
6

![webmaker-18x26-07](https://cloud.githubusercontent.com/assets/12228435/8220811/0e0df032-150c-11e5-9420-5230b8f359e1.jpg)
7

![webmaker-18x26-08](https://cloud.githubusercontent.com/assets/12228435/8220810/0e0b9f3a-150c-11e5-956a-0da8a2177bc6.jpg)
8

**Comment by lovegushwa** [comment]
^ Sorry all, a few blank art boards made it into the last comment. Just fixed it. Now using numbers for each poster to avoid confusion. Comment away.

**Comment by cassiemc** [comment]
@lovegushwa I liked the shadow, it anchors the phone in space, I just thought it was too dark. Should the arm go right to the edge of the page? 

@edrushka @HPaulJohnson Was it deliberate that none of the statements have periods? Feels weird not to have them on the taglines that are actually statements, and I think you could have them even on the fragments. It creates a finality to them that looks good in headlines.

**Comment by edrushka** [comment]
@cassiemc no, not deliberate. Just rushed copywriting ;) We'll quadruple check punctuation for final version.

**Comment by HPaulJohnson** [comment]
Super helpful to see these in layout form. Here's my favorites, ranked: 
- 6 - An app made for you, by you (feel like this one captures an essence of local pride that I like)
- 5 - Imagine the possibilities (this one probably works particularly well with some of the previous designs; more on that below) 
- 1 - Discover. Create. Share (the original, still works)
- 8 - Share what you love with friends (strong but not sure we want to emphasize given sharing functionality may be limited in earlier versions)

RE: design, I'm liking it better without the shadow under the phone. With that shadow I was getting an alien vibe from the arm. Maybe that's still lingering in these versions but the arm is pretty focal and I wonder if there's a way to de-emphasize that and draw more attention to what's on screen. 

Which brings me to my second design comment: I didn't realize how much I'd miss the ice cream bar :) While I like how clean these are, they are missing a human aspect that the versions with the backgrounds had. With some of these headlines it might be nice to have the visual metaphor of sharing the world around you via this app. Wonder if we should revisit that? 

I'm ready/available to discuss any/all of the above. Awesome works thus far. 

(P.S. yes, the copy was a rush job. Just trying to get some variations we can share for feedback before tightening up.)

**Comment by lovegushwa** [comment]
@HPaulJohnson @cassiemc @edrushka 
Tomorrow 1st thing I'm going to push the design, shadows/no shadows, texture etc, additional illustration etc. It's at a 5.5 or 6 right now, we will push it to a 10, no worries. I just need to spend some time on it. (Buttons, stickers, pins and t-shirts are finished so I can get cracking.)

**Comment by HPaulJohnson** [comment]
@lovegushwa thanks! love where this is going and excited to see where we land.

**Comment by HPaulJohnson** [comment]
Meant to add two other small comments re: the URL (mzl.la/webmaker.org). 

Can we make it stand apart so that it doesn't get lost in the block of copy? It's the true CTA of this piece and want to make it as clear as possible. 

I think webmaker.org is probably stronger than the mzl shortlink. I understand using the shortlink when we have less real estate but, here, seems like full URL would reinforce brand and be more memorable.

**Comment by lovegushwa** [comment]
@HPaulJohnson @cassiemc @edrushka  more iterations to come over the afternoon. I'll see if I can make that URL stand out a bit more. (Oh also I took a stab at the headline :)

![screen shot 2015-06-18 at 2 17 14 pm](https://cloud.githubusercontent.com/assets/12228435/8242537/f07e210e-15c4-11e5-86d2-d5088e9935bc.png)
A

![screen shot 2015-06-18 at 3 14 26 pm](https://cloud.githubusercontent.com/assets/12228435/8243556/e83f9380-15cc-11e5-9f31-2b3d84575f54.png)
B

![screen shot 2015-06-18 at 4 21 03 pm](https://cloud.githubusercontent.com/assets/12228435/8244482/25947d5a-15d6-11e5-891d-d7e8b9217ccc.png)
C (starting to experiment with graphic abstractions of the photograph displayed in the app.)

![screen shot 2015-06-18 at 8 16 35 pm](https://cloud.githubusercontent.com/assets/12228435/8246661/3988f18a-15f7-11e5-841d-8b4c6680cefb.png)
D

**Comment by HPaulJohnson** [comment]
Thanks @lovegushwa. I'll wait to see the other iterations to compare and make more extensive comments. 

In the mean time, I think we can just commit to a single version of the body copy. I'm obsessed with having the word download and free so let's go with this: 

Webmaker lets you build original creations on your mobile device in minutes and share them with your friends. Download Webmaker for Android — it's free and open source.

**Comment by lovegushwa** [comment]
@HPaulJohnson ^
Cool, I'll keep using that version of the body copy as iterations progress.

**Comment by HPaulJohnson** [comment]
Cool, I'm digging it (C in particular). 

Forgot to add re: body copy. Think we should also just go with webmaker.org for URL (instead of mzl.la/webmaker).

**Comment by lovegushwa** [comment]
@HPaulJohnson is the link just webmaker.org?

**Comment by HPaulJohnson** [comment]
Yep. I like it because it reinforces the brand a second time. We will likely be reaching people who have never heard of us before so repetition is good. Also, I like that it is a subtle wink to internet.org

**Comment by lovegushwa** [comment]
@HPaulJohnson @edrushka 
Back at it in the morning. Tomorrow we will crack it for sure.

**Comment by lovegushwa** [comment]
![screen shot 2015-06-19 at 1 25 18 pm](https://cloud.githubusercontent.com/assets/12228435/8262794/ee9ba42c-1689-11e5-8600-4425f5b1a0e9.png)
E

![screen shot 2015-06-19 at 1 47 44 pm](https://cloud.githubusercontent.com/assets/12228435/8262792/e9e6648a-1689-11e5-94a9-2a5d42069180.png)
F

**Comment by cassiemc** [comment]
These seem a bit off to me – like there is too much going on, and the yellow hand seems the wrong hue for our market (perhaps too realistic, too peachy-white). Are these patterns/textures being used anywhere in the UI? They feel a bit extraneous to me and at this early stage in marketing the app we should be a little more reflective of the app's feel, though I get trying to inject more personality. The purple to green gradient also looks muddy in the middle. Let's follow up in Whistler? @lovegushwa @HPaulJohnson

**Comment by HPaulJohnson** [comment]
@cassiemc we talked a bunch about the hand with @lovegushwa and @edrushka on Friday. Jordan was going to work with the hue but, generally speaking, the reactions to the hand itself have been mixed. So I'm open to options. We are working against some production deadlines but I trust that in my absence, the three of you can land on something awesome. We should also be as flexible as possible in our schedule so that we get this right (may be that for this first iteration, simple is better). 

For copy, let's keep the "Discover. Create. Share" headline. I have some landing page tests running in Optimizely at the moment with all the variations but none have reached statistical significance as of this morning. I'm going to send the details of that test to @adamlofting and if things change between now and when we go to print we can make a headline swap. 

For URL's, I've created some country specific URL's so we can track performance of downloads from the poster: 

BD: http://mzl.la/discover
BR: http://mzl.la/create
ID: http://mzl.la/share
KE: http://mzl.la/imagine
North America: http://mzl.la/make

**Comment by cassiemc** [comment]
Jordan and I discussed a simpler and more conservative poster design at the workweek after trying a couple different directions. This seems smart given our time constraints. He is going to iterate on possibly including other ghosted ui screens or elements, to emphasize that this is an app poster and not an ad for a cell phone. @lovegushwa can you post the latest here?

**Comment by cassiemc** [comment]
@lovegushwa will also markup the design with guidelines & provide @jaykappa the fonts, sizes, colors, margins, etc.

**Comment by cassiemc** [comment]
Update from today's stand: 

**App Screen/s** – up in the air. Not sure if images of people are appropriate. We need images that will work in all locales. We need help from @xmatthewx (given @vazquez's PTO today and tomorrow) to finalize so I'll set up a conversation for later today. 
**Printer:** @lovegushwa is handling the printing of these. The main time concern is that the UI will need to be translated so we need to choose those screens asap. Also has major implications on the other digital assets in https://github.com/mozilla/webmaker-launch/issues/34
**Deadline:** Jordan is hoping to have this finalized by Wednesday, July 1

**Comment by vazquez** [comment]
Everything is updated on Drive under `webmaker-android -> version 2.0`

`Webmaker-App Content-UI-2015-06-30.sketch`
`Webmaker-Google Play Store Assets-UI-2015-06-30.sketch`
`Webmaker-Mobile-UI-2015-06-30.sketch`
`Webmaker-Landing Page-UI-2015-06-30.sketch`

(give it a few minutes for all files to upload)

**Comment by cassiemc** [comment]
Awesome thanks @vazquez. I don't think I have access to that folder – any way you can add these to 'Webmaker Launch Assets'? Also, @jaykappa is working in CS6. Can you make sure they all have jpg, png or – preferably – svg exports?

**Comment by vazquez** [comment]
I don't have access to Webmaker Launch Assets lol. Matthew, can you add
Cassie to the Webmaker-android folder?

 For just the UI elements though, SVG can definitely be done. However, some
art boards contain images (the people, or the mountains) that prevent them
from being able to be exported in SVG. Matthew, can you help @jaykappa with
that?

On Monday, June 29, 2015, Cassie McDaniel notifications@github.com wrote:

> Awesome thanks @vazquez https://github.com/vazquez. I don't think I
> have access to that folder – any way you can add these to 'Webmaker Launch
> Assets'? Also, @jaykappa https://github.com/jaykappa is working in CS6.
> Can you make sure they all have jpg, png or – preferably – svg exports?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/webmaker-launch/issues/53#issuecomment-116768601
> .

## 

Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez http://twitter.com/iamrvazquez
IRC: ricardo

**Comment by cassiemc** [comment]
We've decided to go forward with two directions:
- **v1: Refined speech bubble.** _Try:_ less contrast with background, an idea bubble instead of a speech bubble, less sharp curves, etc.
- **v2: Less phone more app** _Try_: Make the phone feel like less the subject of the poster (an ad for a phone); could ditch the hand, add hint of other screens, or dial back the detail of the phone.

In both versions, let's go with the current screen on the phone that Jordan is using that has the water (could potentially be other snaps for local environments / cities). In the future, particularly in the digital assets, we might want to test two other types of content – one that has humans and one that has a bit more UI. Not sure if a plan for this is currently in place. cc @edrushka @lovegushwa

**Comment by lovegushwa** [comment]
@cassiemc @edrushka 

v1 (refined speech bubble shape, less contrast)
![screen shot 2015-06-30 at 12 51 10 am](https://cloud.githubusercontent.com/assets/12228435/8426156/362f3764-1ec2-11e5-96f8-e808d047b57a.png)

v1 additional options
![screen shot 2015-06-30 at 12 31 48 am](https://cloud.githubusercontent.com/assets/12228435/8426162/44eafc98-1ec2-11e5-9b92-2faac4b58d66.png)

![screen shot 2015-06-30 at 12 32 03 am](https://cloud.githubusercontent.com/assets/12228435/8426172/63ebed78-1ec2-11e5-9e9b-79ad5db3b147.png)

![screen shot 2015-06-30 at 12 31 39 am](https://cloud.githubusercontent.com/assets/12228435/8426176/689eb6f2-1ec2-11e5-8ce0-e44765001fe8.png)

original
![screen shot 2015-06-30 at 12 31 26 am](https://cloud.githubusercontent.com/assets/12228435/8426182/866dc236-1ec2-11e5-954b-b962ff47426a.png)

v2
![screen shot 2015-06-30 at 12 32 12 am](https://cloud.githubusercontent.com/assets/12228435/8426201/c195db64-1ec2-11e5-8403-5f47c2b1ed73.png)
( also we could use 3 of the 4 screens seen on the app store https://play.google.com/store, Or change the layout and use all 4.)

**Comment by cassiemc** [comment]
Really like the 3-up option, v2, nice work @lovegushwa. Would also be okay with v1, the top option. I think they both make it feel more human (less about the phone) and add a small bit of visual lavour. 

@edrushka can you advise how we should move forward with a decision given @HPaulJohnson is on PTO (unless Paul can comment here)?

**Comment by xmatthewx** [comment]
Looking nice. I'll let this group continue to drive the direction. 

A few thoughts/suggestions on the little details: 
- remove the microphone/speaker dots. I've only ever seen them on htc brand phones. A little line or rectangle would be more universal. 
- maybe make the camera circle less contrasty.  

The text in the app screenshots should be crafted carefully:
- ~~Olympic Mountains~~ >> something more universal? Birthday or Holiday or Graduation 2015
- ~~My grandmothers village~~ >> Sunset with friends (not sure that grandmas conjure ideas of new fun social web. also, it's missing an apostrophe) 
- ~~Pick a destination page~~ >>  Add a link (more clear even if less accurate)

**Comment by KevZawacki** [comment]
+1 to @xmatthewx's three copy suggestions.

**Comment by cassiemc** [comment]
Kev was just looking for your handle! I also like @xmatthewx' suggestions. Can we nail down that first line of copy changes – what would you prefer @kevzawacki between birthday / holiday / graduation?
cc @lovegushwa

**Comment by lovegushwa** [comment]
@cassiemc @xmatthewx @edrushka 
Hi everyone, check out the updated final version. @xmatthewx thanks for the feedback, I incorporated it. I also cleaned up the sunset image a bit and added little slivers of content images to the top, bottom, left and right of the main image. Let me know if it's all good and I'll get it up on the server for Jay.

![screen shot 2015-06-30 at 1 34 55 pm](https://cloud.githubusercontent.com/assets/12228435/8441409/d78a79c4-1f2c-11e5-95e7-85e53cf57b80.png)

**Comment by KevZawacki** [comment]
Let's go with birthday.

**Comment by lovegushwa** [comment]
@cassiemc @xmatthewx @edrushka @KevZawacki 
Hi Everyone, Can some one confirm the final copy? ... Birthday 2015? Also I would like to stay away from numbers since they have the potential to cause problems when translated. (I know that sounds crazy but trust me.)

1
![screen shot 2015-06-30 at 2 18 01 pm](https://cloud.githubusercontent.com/assets/12228435/8442282/f48bf5d8-1f32-11e5-845d-2ad146430047.png)

2
![screen shot 2015-06-30 at 2 17 52 pm](https://cloud.githubusercontent.com/assets/12228435/8442290/faef8ae8-1f32-11e5-80c8-42a48e77b013.png)

3
![screen shot 2015-06-30 at 2 17 31 pm](https://cloud.githubusercontent.com/assets/12228435/8442297/0502dd8c-1f33-11e5-9f8d-dba326b8fda9.png)

4
![screen shot 2015-06-30 at 2 02 36 pm](https://cloud.githubusercontent.com/assets/12228435/8442316/20121ec6-1f33-11e5-8e0d-7d19ec1956cb.png)

**Comment by xmatthewx** [comment]
Project title looks to be a wee bit high, rather than centered in header. Otherwise, looking super nice.

**Comment by lovegushwa** [comment]
@cassiemc @HPaulJohnson @edrushka @jaykappa 
The final artwork is up on the server: Webmaker Launch Assets > PROCESS 

![screen shot 2015-06-30 at 5 20 51 pm](https://cloud.githubusercontent.com/assets/12228435/8444987/a29fbf1a-1f4c-11e5-9c03-264cb81344e0.png)

**Comment by panaggio** [comment]
The last phrase doesn't have any reference to the Web. Is it on purpose?

**Comment by secretrobotron** [comment]
@KevZawacki ^^

**Comment by KevZawacki** [comment]
You're talking about "Webmaker lets you build original creations... free and open source"?

We didn't purposefully exclude a reference to the Web. If we feel it's important to include, we can update the phrase to:

"Webmaker lets you build original creations on your mobile device in minutes and share them on the Web. Download Webmaker for Android — it's free and open source. --> Webmaker.org"  

But we end up with four instances of "Web" in the phrase. Seem like a mouthful?

**Comment by cassiemc** [comment]
@KevZawacki I think it's fine as is, I believe @edrushka / @HPaulJohnson have already passed this copy on to translators and would prefer not to change it at this point. cc @lovegushwa @secretrobotron

**Comment by KevZawacki** [comment]
+1

**Comment by secretrobotron** [comment]
:+1:
