### ISSUE TITLE
Assets for Whistler

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker-launch#55]
These assets are specifically for the Whistler All-Hands
driver: @edrushka
- [ ] stickers
- current status: at printers (Victoria & Portland)
- [ ] pins
- current status: at printers (Vancouver)
- [ ] t-shirts (for people demoing at Science Fair only. **Not** for staff)
- current status: at printers (Victoria)
- [ ] banner for science fair
- current status: at printers (Portland)

cc @secretrobotron @HPaulJohnson

**Comment by edrushka** [comment]
@secretrobotron will this work for the banner?
![purple banner](https://cloud.githubusercontent.com/assets/4515662/8211936/e5982764-14cd-11e5-8d6a-b4d3788bd1eb.jpg)

**Comment by secretrobotron** [comment]
Can this be on a darker shade of blue? #65DBC8 is what @vazquez recommends based on the style guide he's producing.

**Comment by edrushka** [comment]
@vazquez I used the purple from the colour palette 485ECC @100% opacity

**Comment by edrushka** [comment]
Sorry for the rush but we need to R+ this right away to get it to the printer. @cassiemc R? cc @lovegushwa

**Comment by secretrobotron** [comment]
@vazquez and I are R'ing it right meow.

**Comment by lovegushwa** [comment]
Hi all, will have a revised color version up in 2min.

**Comment by lovegushwa** [comment]
@secretrobotron @edrushka  @cassiemc @vazquez

2 different brand colors. 4D8EFF blue and 685ECC purple (The colors pulled from the Google Play store assets.)  

![screen shot 2015-06-17 at 9 22 22 am](https://cloud.githubusercontent.com/assets/12228435/8212768/786441fa-14d2-11e5-881c-1dd5e3faf751.png)

![screen shot 2015-06-17 at 9 22 42 am](https://cloud.githubusercontent.com/assets/12228435/8212772/7e3dc8e4-14d2-11e5-9ff0-36ef2261f0d6.png)

**Comment by vazquez** [comment]
What about using the Plum? The red really becomes vivid on top of that colour.

![feature-graphic](https://cloud.githubusercontent.com/assets/1119821/8212881/59286a7c-14ec-11e5-9add-2b6717d1cf56.png)

**Comment by vazquez** [comment]
I can provide the AI file if you need it @lovegushwa

**Comment by lovegushwa** [comment]
@vazquez, I like Plum ... It's part of the app pallet, we should add it to the marketing pallet. Any one have a Pantone book handy so we can nail this color in CMYK? (It will probably print dark if we use the RGB hex value.)

**Comment by vazquez** [comment]
Oh gosh I don't have that :( how can I help with this?

Plum is being used in the Feature graphic and promo graphic of the Android marketing material, it's already part of the marketing palette.

**Comment by vazquez** [comment]
It seems to be 38, 35, 0, 59 in CMYK

**Comment by cassiemc** [comment]
The plum feels nice. @lovegushwa I'd check with the Vancouver office (@sabrinang) and maybe @vazquez you can ask around Toronto – could be in the back UX meeting room.

**Comment by vazquez** [comment]
Asking FxOS Designers, hang tight.

**Comment by vazquez** [comment]
FxOS Designers are missing, the back room bookshelves don't have a Pantone book. I'll keep searching.

**Comment by secretrobotron** [comment]
This work? http://www.netfront.fr/Services/rgb2pantone/pantone.htm?r=65&g=68&b=104&rgb=
Looks like 5265 is closest.

**Comment by lovegushwa** [comment]
Rad, thanks everyone. Am I clear to go ahead with this? @cassiemc @secretrobotron  @edrushka R?

![screen shot 2015-06-17 at 10 18 49 am](https://cloud.githubusercontent.com/assets/12228435/8213899/486a9d0c-14da-11e5-8c6c-37b64d2e6ee1.png)

**Comment by lovegushwa** [comment]
@vazquez ^

**Comment by cassiemc** [comment]
R+ from me!

**Comment by edrushka** [comment]
R+ print it! :)

**Comment by edrushka** [comment]
cc @jaykappa

**Comment by vazquez** [comment]
R++++++ :rocket:

**Comment by lovegushwa** [comment]
Rad, on the way to the print shop. Thanks everyone.

**Comment by cassiemc** [comment]
I think these are all done, @lovegushwa correct me if I'm wrong! The banner looked super :bomb: awesome at the science fair!
