### ISSUE TITLE
Offline feature needed for emerging markets

### ISSUE THREAD

**Issue by cecilepompei** [mozilla/webmaker-launch#71]
@secretrobotron 

main feedback from 60 participants in Emerging Markets

people cannot use Webmaker because it is only online so far and they generally do not have data on their phone

many people in emerging markets go to (fancy) restaurants and cafes to use the net.
 but the problem is for the ones who cannot afford frequent cups of tea (the majority) in fancy restaurants. they therefore never have access to the internet and rarely buy data for their phones (and surely not to experiment on a new app) since it is too expensive

**Comment by panaggio** [comment]
JTFR, I spoke with @secretrobotron in private about this and we may have the same problem in Brazil.

On the bright side of things, this is already on webmaker-android's radar:
- https://github.com/mozilla/webmaker-android/issues/2005
- https://github.com/mozilla/webmaker-android/issues/954
- maybe other issues I couldn't find.

This is critical, so maybe this label could be added to those issues and the others I couldn't find.

**Comment by secretrobotron** [comment]
Thanks @panaggio.

Yeah, this is definitely something the team is aware of. I'll catch up with @thisandagain to see when we'll be able to land these features.

**Comment by lauradereynal** [comment]
Thanks for the feedback here. This is currently being tackled by the team in https://github.com/mozilla/webmaker-android
