### ISSUE TITLE
Bangladesh GTM - Localize Poster

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-launch#80]
@bellayet @tapuafrad @LauraReynal

We've got a couple more assets that we're hoping to get localized this week so we can print them. Do you think you can help?

We're making a poster, and there are a couple parts of it that need to be translated into sensible Bangla: https://github.com/mozilla/webmaker-launch/issues/53#issuecomment-117377754
- "Sunset with Friends"
- "Discover. Create. Share."
- "Webmaker lets you build original creations on your mobile device in minutes and share them with your friends. Download Webmaker for Android — it's free and open source."

cc @kevzawacki @edrushka

**Comment by bellayet** [comment]
@tapuafrad is no longer active. I am adding @maktrix here.

**Comment by KevZawacki** [comment]
Hi @maktrix , hoping you can assist with one more translation. 
We'd like to translate "text size," in the context of this post (first screen): https://goo.gl/Z1R2Il
Thanks!

cc @lovegushwa

**Comment by lovegushwa** [comment]
@secretrobotron @LauraReynal @kevzawacki @edrushka
Any word on the Bangladesh translation? I need it by end of day Friday because we are going to press. Thank you!!

**Comment by lauradereynal** [comment]
I think @maktrix or @jaggedzak or @bellayet or maybe @asif21 or @srdesh @Amena-Islam 
could help ? 
Let us know  - thanks ! 

Ps : @lovegushwa Friday is a holiday in Bangladesh, so we might not see anything until Sunday

**Comment by lauradereynal** [comment]
ok update from @bellayet : We already working on that. Reviewing the translated strings.

**Comment by bellayet** [comment]
"Sunset with Friends"
"বন্ধুদের সাথে সূর্যাস্ত"

"Discover. Create. Share."
"আবিষ্কার। সৃষ্টি। শেয়ার।"

"Webmaker lets you build original creations on your mobile device in minutes and share them with your friends. Download Webmaker for Android — it's free and open source."
"ওয়েবমেকার এক মিনিটেই আপনার মোবাইল ডিভাইসে মৌলিক সৃষ্টিকর্ম তৈরি এবং বন্ধুদের সাথে তা শেয়ারের ব্যবস্থা করে। অ্যান্ড্রয়েডের জন্য ওয়েবমেকার ডাউলনোড করুন — যা উন্মুক্ত এবং ওপেন সোর্স।"

"text size"
"লেখার আকার"

@maktrix @jaggedzak @asif21 @srdesh @Amena-Islam if you have any suggestions regarding the translations please let us know.

**Comment by lovegushwa** [comment]
Thank you so much for the translation and help @bellayet !!
Please review the poster and postcards for accuracy. Files will release to the printer tomorrow morning the 7th (Bangladesh time.) 

POSTER
![webmaker-poster4](https://cloud.githubusercontent.com/assets/12228435/8532536/af05116a-23e3-11e5-913a-e79d6bd04fc6.jpg)

POSTCARD FRONT
![webmaker-postcard-5x7in-proof7](https://cloud.githubusercontent.com/assets/12228435/8532697/edd5da2c-23e4-11e5-9c7a-55e77168d57c.jpg)

POSTCARD BACK
![webmaker-postcard-5x7in-proof8](https://cloud.githubusercontent.com/assets/12228435/8532701/f2eb02a8-23e4-11e5-95d6-c094e5d86e9e.jpg)

CC @LauraReynal @secretrobotron @KevZawacki

**Comment by bellayet** [comment]
Please don't print the poster. Your fonts are not working. Texts are completely broken down. Please take help from the designer who worked on the poster for Firefox OS launching. Make sure the texts working properly before printing.

**Comment by lovegushwa** [comment]
Thank you !!! @bellayet 
@secretrobotron @KevZawacki can you help me sort this out?

**Comment by secretrobotron** [comment]
Just sent an email to some people to find out how to do this. Will report back when I've got an answer.

**Comment by lovegushwa** [comment]
@bellayet 
Here is a screenshot of what I see when looking at your translated text in my browser window. Is this text displaying correctly?

<img width="811" alt="screen shot 2015-07-06 at 5 15 45 pm" src="https://cloud.githubusercontent.com/assets/12228435/8536193/d685fa6e-2402-11e5-8aba-8532cbeb1812.png">

**Comment by lovegushwa** [comment]
@bellayet 
Please also confirm if this interface text is displaying correctly.
<img width="471" alt="screen shot 2015-07-06 at 5 43 11 pm" src="https://cloud.githubusercontent.com/assets/12228435/8536456/817dbfee-2406-11e5-9e8e-daa68e452e2f.png">

**Comment by peiying2** [comment]
A general comment, if we have these posters in other languages, let's also get them reviewed before releasing them.  Sometimes accents could be wrong or missing.

**Comment by maktrix** [comment]
Bengali is written in "Complex Script"; Unicode has our complex script included, we use Unicode to write Bengali in places on the Internet and Web; as Belayet wrote his mail to translate strings through Unicode Bengali.

Unfortunately, most of the popular desktop publishing applications (DTP Apps) does not support UNICODE Bengali. So, copying text from what we wrote, will display this kind of "nonsense rendering".

One have to use Bengali ASCII fonts for illustrations purpose with DTP Apps, AFTER converting the Unicode text into legacy ASCII format.

I regret to disagree the way things are getting done within short period of time and putting us at the brink of deadline to act and comment on important issues. It's not only the text rendering; we might end up with poor presentation of Bengali translation in posters, as we are not getting enough time to assess and foresee how would these publication might finally appear, how a non-Mozillian citizen of my country would react to possible funny lines in his Language.

Just for record, I am not satisfied with the translations specific to the poster and any printable for Webmaker for android launch in Bangladesh. It's not that easy to localize or translate, promotional punch lines / catchphrases into a language with such diverse culture in Bangladesh. FYI, I am Mozilla bn-BD (Bengali Bangladesh) locale (localization) lead. We did excellent work during Firefox OS launch in Bangladesh; everyone liked those lines in outdoor billboards, posters, pamphlets, web banners and so on. Those translation became universal. just my 2c.

**Comment by lovegushwa** [comment]
@maktrix Thank you. I completely agree that translation and localization should not be rushed. The current situation is not ideal.

Below is the exact text we need translated and then shared in a format that does not corrupt. 
Can you help us get a working translation that we can forward on to a designer that understands Bangla? (perhaps a .rtf file?)

POSTER & POSTCARD
- Discover. Create. Share.
- Webmaker lets you build original creations on your mobile device in minutes and share them with your friends. 
- Download Webmaker for Android. It’s free and open source.

APP SCREEN
- Sunset with Friends
- text style
- edit text
- text size
- font
- color
- Set Destination

CC @bellayet @secretrobotron @HPaulJohnson

**Comment by lovegushwa** [comment]
@bellayet  Can you place your translation in this google doc? We are having issues with UNICODE script not displaying correctly and pasting the script into a Google doc should be a good workaround.

https://docs.google.com/document/d/1mPIRPj1thXT16fHUhkM3IpmMUmkM7s5PAt1uI_OH9GI/edit?usp=sharing

CC @maktrix @secretrobotron @HPaulJohnson

**Comment by giuseppe-828** [comment]
@bellayet Once you place the Bengali strings into the spreadsheet, I'll move them into InDesign.

I'd love to be able to do a screenshare/Google Hangout so we can quickly adjust and confirm the results. Let me know what times would work best for you.

**Comment by lovegushwa** [comment]
@tlow87 @bellayet  I used the Adobe world ready single line composer feature in indesign and I think resolved the issues with the script breaking. Please advise if the poster and postcard now read correctly!

POSTER
![webmaker-poster4-final](https://cloud.githubusercontent.com/assets/12228435/8559975/f92d8cc4-24c7-11e5-93c7-fb446aa4cf41.jpg)

POSTCARD FRONT
![webmaker-postcard-5x7in-final](https://cloud.githubusercontent.com/assets/12228435/8560017/6d98f1e8-24c8-11e5-8ebf-7d380875a653.jpg)

POSTCARD BACK
![webmaker-postcard-5x7in-final2](https://cloud.githubusercontent.com/assets/12228435/8560019/747319ee-24c8-11e5-951a-2233bb67973f.jpg)

**Comment by giuseppe-828** [comment]
I believe you must enable the World-Ready Composer, but it may also be useful to follow the instructions under Set Indic Preferences (http://blogs.adobe.com/vikrant/2012/05/indesign-cs6-indic-support-and-preferences/). Fingers crossed!

**Comment by secretrobotron** [comment]
@maktrix @bellayet can you check out the poster above again? @lovegushwa spent some more time to get those characters right.

**Comment by peiying2** [comment]
Mak and Bellayet, Webmaker, according to brand guideline, needs to be kept in English.  You can put the translated names in parenthesis as an alternative.

**Comment by secretrobotron** [comment]
@jaggedzak had a look at the posters — they looks alright. Nothing funny anymore.

**Comment by secretrobotron** [comment]
@peiying2 good catch. @KevZawacki @HPaulJohnson @cassiemc thoughts?

**Comment by cassiemc** [comment]
Seems right to keep Webmaker in English (don't think I'd include the translated names)

**Comment by HPaulJohnson** [comment]
I agree. Pretty standard to leave brand/wordmark untranslated.

**Comment by peiying2** [comment]
Well, brand/product name localization is a hot topic that we are discussing right now.  This is a major issue for lots of  languages, especially those based on non-Latin scripts. Here is the discussion on that: http://tinyurl.com/qh6xe4u.
We are conducting a survey with the l10n communities on this so we can revisit the current guidelines and look into possible exceptions with Brand/Creative team's approval.

**Comment by cassiemc** [comment]
This is an awesomely resourceful doc @peiying2 thank you for sharing that! Would love to be kept in the loop on that discussion. Is there a bug somewhere I can add myself to the cc list?

**Comment by KevZawacki** [comment]
Hi @maktrix and @peiying2, 

We're finalizing a few more Webmaker assets (https://github.com/mozilla/webmaker-launch/issues/34), and hoping you can help translate a few phrases:

-Download The App
-Download
-Webmaker lets you build and share original content on your smartphone. Start creating in minutes.
-Learn More

Thanks for your help!
cc @jaykappa

**Comment by peiying2** [comment]
@cassiemc, please add yourself to this bug: 939902.  I also would check who else have asked me to get access to the document.  I will inform everyone when we have another meeting with branding/creative team.

**Comment by peiying2** [comment]
@maktrix @bellayet, Please respond to KevZawacki ASAP.  I found a few exact matches in https://transvision.mozfr.org, but would be reluctant to recommend anything without your review.

**Comment by maktrix** [comment]
-Download The App
-এপটি ডাউনলোড করুন

-Download
-ডাউনলোড

-Webmaker lets you build and share original content on your smartphone. Start creating in minutes.
-Webmaker আপনার স্মার্টফোনে মৌলিক কনটেন্ট তৈরী ও শেয়ার করতে সহায়তা করে। মিনিটের মধ্যেই তৈরী করুন।

-Learn More
-আরও শিখুন

**Comment by KevZawacki** [comment]
Thanks very much, @maktrix

**Comment by jaykappa** [comment]
@maktrix  would you mind reviewing the following to ensure translation was applied appropriately (I fear some copy and paste issues may have occured):

![2015-webmaker-twitter-1760x800-ban](https://cloud.githubusercontent.com/assets/1036635/8707851/433be98e-2b06-11e5-9210-798d75557e5a.jpg)
![2015-webmaker-webbanners-horz-468x60-ban](https://cloud.githubusercontent.com/assets/1036635/8707854/43409402-2b06-11e5-8efa-50982968a1d1.jpg)
![2015-webmaker-webbanners-horz-728x90-v3-ban](https://cloud.githubusercontent.com/assets/1036635/8707852/433eb15a-2b06-11e5-82ab-6189947dabad.jpg)

cc @KevZawacki @secretrobotron @lovegushwa

**Comment by tapuafrad** [comment]
Again, texts have been broken down completely.

**Comment by giuseppe-828** [comment]
@maktrix Below is what I'm able to get out of InDesign. If these are correct, perhaps I can take a shot at it.

![bengali](https://cloud.githubusercontent.com/assets/5862593/8728673/65d5ce3e-2b9b-11e5-8aeb-021553b92008.png)

**Comment by maktrix** [comment]
@tlow87 the characters and vowels rendered perfectly well. These are correct.

Can I suggest a change in translation for the sentcene, "webmaker lets you build and share original content on your smart-phone. Start creating in minutes." If it is possible change the previous translation with, "Webmaker আপনার স্মার্টফোনে মৌলিক কনটেন্ট তৈরী ও শেয়ার করতে সহায়তা করে। মিনিটের মধ্যে তৈরী করা শুরু করুন।"

**Comment by giuseppe-828** [comment]
@jaykappa Would you mind sending me the latest InDesign files you were working with? And is there an English reference to make sure I'm pasting the right words in the right spot?

**Comment by giuseppe-828** [comment]
@maktrix Would you mind ensuring that all the strings I'll need are in this document? https://docs.google.com/document/d/1mPIRPj1thXT16fHUhkM3IpmMUmkM7s5PAt1uI_OH9GI/edit?usp=sharing

**Comment by maktrix** [comment]
@tlow87 done.

**Comment by lovegushwa** [comment]
@tlow87 your the best! Jay created the banners in Illustrator, let's hope it's a simple fix like the posters in in-design. Please checkout these links:

https://drive.google.com/file/d/0B0h-htXn09OHY0Ytckgza0I3UGc/view?usp=sharing
https://drive.google.com/file/d/0B0h-htXn09OHMzBzRzhHNmR2TjA/view?usp=sharing

CC @jaykappa

**Comment by lovegushwa** [comment]
Hi @maktrix @tapuafrad  I think I have the issue resolved, can you confirm? Thank you!

<img width="940" alt="screen shot 2015-07-17 at 6 04 52 pm" src="https://cloud.githubusercontent.com/assets/12228435/8759676/ed469bf0-2cae-11e5-84b1-49994d8204d1.png">

<img width="1201" alt="screen shot 2015-07-17 at 6 07 03 pm" src="https://cloud.githubusercontent.com/assets/12228435/8759677/f39b29da-2cae-11e5-9105-dc4c126d03f4.png">

**Comment by lovegushwa** [comment]
^ @secretrobotron @KevZawacki

**Comment by maktrix** [comment]
@lovegushwa the artworks displayed Bengali characters rendered perfect. You can resolve the issue now.

**Comment by lovegushwa** [comment]
Excellent @maktrix , thank you!!

**Comment by secretrobotron** [comment]
:yellow_heart:
