### ISSUE TITLE
Prep announcement on Terms update (CC license)

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-launch#90]
We will soon release new terms of service and need to notify users of the changes, particularly around the new CC license. 

@HPaulJohnson - do you have other emails going out to all users? We can include this statement in another message as long as it has prominence. Or, we can send it separately if we want to explain the spirit of CC a bit more.  

The one open question that will impact the language of the announcement: whether prior content will get the new license. I’m guessing the answer is yes, from both a tech and community perspective, but that’s a question for @simonwex, @ldecoursy, and others.

**Comment by HPaulJohnson** [comment]
@xmatthewx when you refer to all users do you mean anyone who has downloaded the new Webmaker app? This is related to your second question, I suppose, re: whether this is retroactive. 

Is there specific legalese that we need to send? And, does it need to be communicated via email or can it be done via blog?

The current Mozilla template that we use for many of our mailing already has this small print: 
"Copyright © 2015 Mozilla Foundation Content available under a Creative Commons share-alike license V2.0"

Going forward we should probably update that, at least on our Webmaker email templates, to something like "Mozilla Foundation and Webmaker content..."

**Comment by xmatthewx** [comment]
The changes to the TOS will impact new Android users as well as anyone who made something on Thimble etc in the past. We could announce the update in the tools, but that would require a bunch of engineering. Let's meet to discuss.

**Comment by xmatthewx** [comment]
announcement requires terms to be posted: https://github.com/mozilla/webmaker-browser/issues/152

**Comment by ldecoursy** [comment]
cc @hannahkane re: Thimble.

I might suggest a separate but simple email to registered users a la the examples below, but in the spirit of web literacy, and like @xmatthewx's suggestion above, include some tips/tidbits about CC and what TOS is in general.

![screen shot 2015-07-13 at 9 28 40 am](https://cloud.githubusercontent.com/assets/4885898/8650571/a55a79a8-2941-11e5-9195-ea9c75807a3e.png)
![screen shot 2015-07-13 at 9 28 49 am](https://cloud.githubusercontent.com/assets/4885898/8650572/a7316c5a-2941-11e5-81f6-e6a9ebdb36ac.png)

**Comment by hannahkane** [comment]
+1 to an email to all users. Also, just added a ticket to Thimble repo to link to TOS from footer (https://github.com/mozilla/thimble.webmaker.org/issues/696)

**Comment by HPaulJohnson** [comment]
Agreed. Draft copy to be circulated tomorrow. Mailing date tentatively set for 7/18.

**Comment by HPaulJohnson** [comment]
We have some draft copy but also some lingering questions/concerns.

https://etherpad.mozilla.org/cc-tos-update-email

Main concern is around partners who have contributed content and will be impacted by this change in that it retroactively covers existing content. To mitigate those concerns two questions: 
- A justification for why we are making this change? We'd want to add this to the communication to give context why this change is a positive one for existing users. 
- Will there be anyway for people to understand or measure how there content is being used under this license. For example, an external partner creates curriculum and would like to understand better how/where it's being used outside of Webmaker. 
- If a partner doesn't want their content to be licensed under these new terms what are there options? Would they need to delete their content or even their account?

cc: @KevZawacki

**Comment by HPaulJohnson** [comment]
cc: @secretrobotron - hopefully you can help us get some of these questions answered?

**Comment by xmatthewx** [comment]
@HPaulJohnson - 
1. I added some notes to the pad in response to your first bullet on justification. We might ping Ryan or Mari to see if they have some language crafted already.  
2. On the second point, no reuse is easy to track on the nets. A CC license might make it a bit easier, but it certainly doesn't make it more likely that people will steal a curriculum and not give credit. What's to stop someone from taking something under the current license? 
3. On the third bullet -- I wonder if we can add something to the terms like "all content CC-etc unless otherwise noted." This would be difficult to offer end users, but might give us some flexibility for key partners.

**Comment by HPaulJohnson** [comment]
Updated copy here: https://etherpad.mozilla.org/cc-tos-update-email

@KevZawacki is reviewing and then we'll send to Abigail for final approval. Plan is to send to users of the current Webmaker app on Wednesday if possible.

**Comment by HPaulJohnson** [comment]
Final email here: https://docs.google.com/document/d/1UO1AAG-XGA2Mz4U3lWPmL-JOCbs_EJWP4if9j5zfIa8/edit. Plan is to send this on Wednesday or Thursday this week (8/5-8/6). 

New terms need to be updated and posted/linked on 8/14: Final, legal approved TOS are here: https://mail.google.com/mail/u/0/#search/abigail/14ead562a60f8b85?projector=1.  

For the email, prior to 8/14, they should be available somewhere on site so we can include a link in email. @xmatthewx can you update and provide the final link?

**Comment by xmatthewx** [comment]
Thanks @HPaulJohnson. Can you reshare final terms? Link above doesn't work.

**Comment by HPaulJohnson** [comment]
Abigail made one final tweak last night so here is the final version: 

https://drive.google.com/a/mozilla.com/file/d/0B_MJiF6wUoWPaWotV2Y3RzM3V0xQZEtQMzNCbVE5OVpRYlhJ/view?usp=sharing

**Comment by xmatthewx** [comment]
For now, link is: https://beta.webmaker.org/#/legal

Status of revisions here: https://github.com/mozilla/webmaker-core/issues/442

**Comment by HPaulJohnson** [comment]
@xmatthewx the link above doesn't reflect the changes in the gdoc? when will that happen as it's a blocker on sending the email given the link needs to be included.

**Comment by xmatthewx** [comment]
@thisandagain will post the changes in near future. task for that is here: https://github.com/mozilla/webmaker-core/issues/442

If @mmmavis is available, should could do it as well.

**Comment by mmmavis** [comment]
@xmatthewx is this just copy updates? If it is I should have time to work it :smile: (I'm in SF this week for fundraising stuff so I won't be very responsive on GitHub tickets)

**Comment by xmatthewx** [comment]
@mmmavis - yes, just copy edits. link posted to https://github.com/mozilla/webmaker-core/issues/442. thanks!

**Comment by HPaulJohnson** [comment]
What the latest on getting these updated?

We need to send out the email in the next 2 days to make sure we do it at least 10 days before it goes live.

**Comment by thisandagain** [comment]
We should be able to get the updated TOS landed later today.

**Comment by thisandagain** [comment]
Updated TOS is up on staging. @HPaulJohnson can you give me a second set of eyes before I roll this to production? http://webmaker-desktop-staging.herokuapp.com/#/legal

**Comment by HPaulJohnson** [comment]
@thisandagain looks good to me. thx.

**Comment by thisandagain** [comment]
@HPaulJohnson Ok. This is now live in production: https://beta.webmaker.org/#/legal

**Comment by HPaulJohnson** [comment]
great. email to go out to Webmaker app users tomorrow a.m with a notification.

**Comment by mmmavis** [comment]
@thisandagain @xmatthewx @HPaulJohnson oops sorry this got buried in my inbox.  Thanks for updating it @thisandagain
