### ISSUE TITLE
Build - Webmaker Email Template for BSD

### ISSUE THREAD

**Issue by HPaulJohnson** [mozilla/webmaker-launch#91]
Description: Create a new email template for BSD that utilizes new Webmaker branding. 

Driver: @HPaulJohnson
Design: @lovegushwa

NOTE: for now we will use Mozilla branded template along with Webmaker email callout graphic being finalized now. This template would replace and/or be tested against that approach and be used for transactional emails where HTML templates are supported.

**Comment by lovegushwa** [comment]
@HPaulJohnson @cassiemc 
1. Any good benchmarks for this and or where can I find the Mozilla brand email template?
2. I assume I can use the email content from the partners kit Jay is working on?

I found these searching "email" on https://assets.mozilla.org/portal/assets/
![screen shot 2015-07-09 at 4 36 35 pm](https://cloud.githubusercontent.com/assets/12228435/8609336/c24b1572-2658-11e5-95f6-fa5dd33460d9.png)
![screen shot 2015-07-09 at 4 36 08 pm](https://cloud.githubusercontent.com/assets/12228435/8609337/c25d502a-2658-11e5-9e77-a6f09ea6a5b9.png)

**Comment by HPaulJohnson** [comment]
@lovegushwa unfortunately, Firefox uses a different email platform at the moment so those templates might not be transferable. I'll send you some samples directly from BSD for reference (Mozilla template and old Webmaker template).

I'm just looking for the wrapper here so don't worry too much about what goes inside copy-wise. It would be fine to use what's in the partner kit as placeholder though. 

In terms of BSD expertise, I know @sabrinang and @mmmavis have some experience designing/building BSD templates in the past so you might want ping them re: tips/tricks here.

**Comment by sabrinang** [comment]
We planned a BSD templates previously for teach the web ( the old bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1113753 )

Redpen here: https://redpen.io/sned34e7d965da87ac
![teachtheweb_email_template](https://cloud.githubusercontent.com/assets/2492510/8609595/39feeadc-265c-11e5-8290-2b8fb8b6bd75.png)

From what I remembered BSD had some limitations so it didn't end up looking exactly like the mockup.
@mmmavis would know more details about the technical challenges.

**Comment by mmmavis** [comment]
Heyyy @lovegushwa 

Email templates are very tricky to design/implement as clients render them (hugely) differently.  :cry: :cry: :cry: And BSD doesn't make it any easier for us.

**Rule of thumb** ...

### DESIGN LIKE YOU ARE STILL IN THE EARLY 90s :sob:
- The safest way to make sure email template gets rendered as close as what we expected is to code everything in **nested `<table>`**.
  - forget about responsive design using `media query`, not many clients support this
  - that said, I strongly advocate for a **1-column** layout
- There are tons of restrictions around CSS too 
  - forget about fancy visual treatment, e.g,. gradients, shadows, animations... etc
  - should avoid custom fonts, so things like FontAwesome is a no no

If we could, we should have something **as simple as possible**.  All BSD has is a (janky) rich text editor for email composers to **insert** text and images into ONE SINGLE SECTION in the template.  This suggests that the template should NOT include anything that requires email writers to _modify_ when they write the emails. 

For example, the Teach The Web template has multiple non-stationery sections (details of the Talk, speakers info, speaker headshot, link to "Learn More"). To replace content while preserving the styling/formatting, email writers will have to _modify_ things in the "source code" instead and BSD often breaks the template if we do so.

Sorry I think my explanation sounds confusing but think of it as you are composing a blog post on a WordPress site - you have no control over the site's sidebar or footer, the only thing you have access to is the body content of your post.

I hope this makes sense. :sweat: Let me know if it's not :grin: 

FYI, this is how that janky editor looks like
<img width="1011" alt="screen shot 2015-07-09 at 6 12 14 pm" src="https://cloud.githubusercontent.com/assets/2896608/8610392/745b8168-2666-11e5-8d09-25f34ad23e66.png">

**Comment by mmmavis** [comment]
@HPaulJohnson @adamlofting will we need to include GA script as well?

**Comment by lovegushwa** [comment]
@HPaulJohnson @mmmavis @sabrinang Thanks for the benchmarks and great direction!

**Comment by cassiemc** [comment]
FYI here is an old file I did for Login. I don't think it ever got implemented. Assets are here: https://www.dropbox.com/sh/6bivzh6jj9mhq3i/AABDz0q2flIXUZ1u4GOs18WGa?dl=0
![teach-welcome-email-approved](https://cloud.githubusercontent.com/assets/1186326/8625875/68c5c3aa-270f-11e5-8d21-d75fb2ba5555.jpg)

**Comment by adamlofting** [comment]
> will we need to include GA script as well?

GA tracking is added at the time of email build (using the template) so we don't need to worry about this at the template building stage.

I'd advocate for making this 'template' _extremely simple_ given the number of people who browse and triage emails on their phones first these days (and our mobile-first / mobile-only target market).

**Comment by lovegushwa** [comment]
@HPaulJohnson @cassiemc @flukeout R?

v2 up on redpen!
https://redpen.io/p/jwde743af98c04ef93

v1 for reference
https://redpen.io/p/msf102420595578352

**Comment by HPaulJohnson** [comment]
I'm feeling good about these. I think they will serve us well for an initial test of copy vs. image. My main question is still about how flexible they are, particularly the copy-heavy version, as a template. If we want to add more or less copy, change headlines/subheads, etc how much of this is image-based or static vs. easily editable copy?

**Comment by lovegushwa** [comment]
@HPaulJohnson 
Currently the copy heavy version, the body copy will be easy to change, the headlines will need to be images. It's tricky, the bold headline in Fira really is half of the brand so doing headlines with HTML text will limit us to websafe fonts and have a huge negative visual impact.

@mmmavis 
Can you elaborate on why we are using BSD since it's so limited? Also many MOCO emails look much richer so I imagine they are not using BSD?

**Comment by adamlofting** [comment]
BSD is our current email platform. We're moving to a shared platform with MoCo this quarter, but it's not ready yet.

**Comment by HPaulJohnson** [comment]
@lovegushwa we need a version that can be used in BSD for the short-term (launch at least). Want to make sure what we have can work in BSD?

We'll need to build a different set of templates for Exact Target, though I'm not sure the design spec's or technical details on that (we'll probably have to work with someone from the MoCo email team to figure that out). @adamlofting has started a ticket for the ET templates here: https://github.com/MozillaFoundation/mofo-crm/issues/9#issuecomment-122915384

**Comment by lovegushwa** [comment]
@HPaulJohnson @mmmavis @flukeout R?

I adjusted the email templates for BSD. (One column, Trebuchet instead of Fira for most copy.)
I think we can use the v2 for ET when that comes around.

Please post your comments here, I'd like to close this issue tomorrow if possible :)
https://redpen.io/p/kp13152a5476f5ed43

**Comment by mmmavis** [comment]
Lovely! Thanks @lovegushwa ! I think https://redpen.io/phef42b5becaf57459 should work well under BSD's restrictions :wink: One ask - can you mark what sections stay stationery(e.g., template without sample content)?

**Comment by mmmavis** [comment]
@HPaulJohnson do you know when we plan to send out the emails?

**Comment by HPaulJohnson** [comment]
@lovegushwa looking good! I would also like to understand what sections are editable in BSD. 

@mmmavis still trying to figure out a launch date. Ideally this goes out shortly after we remove the Beta label from the app and do our big marketing push (blog, social, snippet, etc). We are going to determine a new date for all of that by end of week, I hope.

**Comment by lovegushwa** [comment]
@HPaulJohnson @mmmavis @flukeout R?  (need that R+ if possible :)

v4
https://redpen.io/p/td1f421a045335d8ef

**Comment by flukeout** [comment]
Nice work @lovegushwa - these look solid to me.

**Comment by mmmavis** [comment]
Lovely! R:heavy_plus_sign: Let's just go with it and work on adjustment if BSD complains.

**Comment by HPaulJohnson** [comment]
Looks good to me. Thanks!

**Comment by lovegushwa** [comment]
Awesome! :)  @mmmavis let me know what you need. I can provide a bit of markup if you like.

**Comment by mmmavis** [comment]
(I'm not sure if I will be the person who's going to build this)

@lovegushwa 
It would be helpful if we could create a separate build ticket and attach all the assets there! (@HPaulJohnson is there such ticket already?)  Also I'm still curious about which parts in the mockup are stationery :wink: Maybe attaching a mockup _without_ any sample content would help? :bowtie:

**Comment by lovegushwa** [comment]
@mmmavis I just converted this to a build ticket. Will post markup and assets soon.
@HPaulJohnson can you figure out who will build these?

**Comment by simonwex** [comment]
Hey @mmmavis it'd be great if you could do this to help push the Webmaker release over the line. Do you have the bandwidth?

**Comment by mmmavis** [comment]
@simonwex yea I should be able to. Thoughts on how we should QA this? (please comment in https://github.com/mozilla/webmaker-launch/issues/93)

**Comment by mmmavis** [comment]
Oh and can someone assign this ticket to me plz? :grimacing:

**Comment by mmmavis** [comment]
hey @lovegushwa how are the assets coming along? :bowtie:

**Comment by lovegushwa** [comment]
Hi @mmmavis , you can download updated assets from the link below, please let me know if you need anything / any additional markup.

https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvMmxzeVczQkN0bUk&usp=sharing

**Comment by mmmavis** [comment]
cool thanks @lovegushwa!  If it's possible, would you mind attaching a mockup **without** any sample content? It will greatly help me understand which sections of the design have to be built as part of the template. :grin:

**Comment by lovegushwa** [comment]
Hi @mmmavis , the long text email makes most sense as a dynamic template. Please see below (it's also now on the drive.)

<img width="1024" alt="webmaker-email-content" src="https://cloud.githubusercontent.com/assets/12228435/8918271/e97808fa-346b-11e5-8847-90573d96deb6.png">

**Comment by mmmavis** [comment]
hey @lovegushwa mind attaching the updated design here and flag me once you have a chance? :+1: :smile:

**Comment by lovegushwa** [comment]
@HPaulJohnson @mmmavis please see the updated design. Everything should now work if a email client renders text in black (Mavis called out this issue during work week). Please get the updated assets here:

https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvRFdOSGRDTFM2Qk0&usp=sharing

<img width="1024" alt="webmaker-email-v8-1" src="https://cloud.githubusercontent.com/assets/12228435/9182701/2da8ebe4-3f60-11e5-864a-e8b16ffabad9.png">

**Comment by HPaulJohnson** [comment]
Thanks, @lovegushwa 

Question: will the 2 "download the app" and floating phone image be available as separate images that I can simply insert into the body of the email when I add copy to template? We did something similar with latest Maker Party emails, so I think yes. 

@mmmavis does this work for building a template? If so, what's the timeline and eta for having this available in BSD? Will plan launch email around the availability of the template.

**Comment by lovegushwa** [comment]
Question: will the 2 "download the app" and floating phone image be available as separate images that I can simply insert into the body of the email when I add copy to template? We did something similar with latest Maker Party emails, so I think yes. 

Yes I think so @HPaulJohnson, @mmmavis can you confirm?

**Comment by mmmavis** [comment]
@HPaulJohnson I'm aiming to have this ready by EOD tomorrow (Tuesday).  And yup you will be able to insert copy and images into the light purple section in this template.  I would suggest that we run test using Email on Acid before we send out the email to make sure things render properly in most email clients.  I can share creds with you @HPaulJohnson

**Comment by HPaulJohnson** [comment]
@mmmavis - excellent, thank you!

**Comment by mmmavis** [comment]
Hey @HPaulJohnson I think you can start composing the email.  The BSD email template is called "Webmaker Email Template 2015"(we can rename this if you find this name confusing).

Let me know if you need help or clarification.

(I'll forward you the Email on Acid credential in a bit)

**Comment by HPaulJohnson** [comment]
thanks, @mmmavis - I'll start testing it shortly and let you know if I run into any issues.

**Comment by mmmavis** [comment]
cooooool, just forwarded creds to you.  check your inbox :dancer:

**Comment by HPaulJohnson** [comment]
playing around with it now in BSD and it's working pretty well. 

@lovegushwa can you send me the "download the app" image and the floating phones image so I can include those in the tests?

**Comment by lovegushwa** [comment]
@HPaulJohnson you will find the floating phone image here:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvRFdOSGRDTFM2Qk0&usp=sharing

And the download the app image here:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvNEx1S1FkRFlEUm8/view?usp=sharing

**Comment by HPaulJohnson** [comment]
thanks @lovegushwa

**Comment by HPaulJohnson** [comment]
Calling this one complete.
