### ISSUE TITLE
Make sure E-mail template get rendered properly across clients

### ISSUE THREAD

**Issue by mmmavis** [mozilla/webmaker-launch#93]
@adamlofting

E-mail templates are tricky to design and to implement due to various restrictions different e-mail clients have.  Do you know if there's any tool that can help us test/preview the new Webmaker e-mail template?

**Comment by adamlofting** [comment]
I've used testing that's built into email tools in the past, but I've heard good things about Litmus: https://litmus.com/email-testing

**Comment by mmmavis** [comment]
do you know if our new platform has any testing feature that we can leverage? If not I wonder if we can subscribe Litmus.  Using a custom e-mail template without proper testing worries me a lot :confounded: Maybe for now we can try Litmus's one month subscription?

/cc @simonwex

**Comment by adamlofting** [comment]
> do you know if our new platform has any testing feature that we can leverage?

I've tried looking around in SFMC (aka Exact Target) and the [documentation suggests](http://help.exacttarget.com/en/documentation/exacttarget/inbox_tools/) it might be something available as an add-on, but I'm not sure if it's a feature we have currently. I'll ping Jess at MoCo to ask, but for now assume that we don't have this in our tools.

**Comment by adamlofting** [comment]
Good news! MoCo have an account at http://www.emailonacid.com/ which we can use. I will share creds offline.

**Comment by mmmavis** [comment]
Oops, I think we can close this ticket now!
Email on Acid is awesome! Thanks for checking with MoCo on this, @adamlofting :wink: :+1:
