### ISSUE TITLE
Move graphic assets to permenant home

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker-launch#94]
All the Webmaker launch assets are currently stored in a Google Drive folder linked to my Moz account. This isn't ideal in case I get hit by a bus, or suddenly decide to move to Tahiti :palm_tree: :tropical_drink: :palm_tree:

@xmatthewx do you have a recommendation for a permanent home? @sabrinang do you know if the DAM ever got finished?

cc @lovegushwa @cassiemc (who's on PTO)

**Comment by xmatthewx** [comment]
@edrushka you can share the entire folder. You can give read/write access to everyone with a Mozilla address. Also, pretty please give me read/write/participate access to your Tahiti destination.

**Comment by lovegushwa** [comment]
@xmatthewx @edrushka 
I set up a new folder the MOFO design shared drive. Also I'm pulling together a deck today that shows the comprehensive campaign.

https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvOGRoYVBVY3hCdWs&usp=sharing

**Comment by HPaulJohnson** [comment]
@lovegushwa in the promo kit (formerly known as partner kit) we link to a dropbox of shareable assets for community and partners. We need to determine what assets we should add to that dropbox (which I've created). Once you have the deck maybe we can run through and decide what to include for promo kit.

**Comment by lovegushwa** [comment]
@HPaulJohnson cool, yes we can do that. I already have all the .png files organized separately so it should be a snap.

**Comment by lovegushwa** [comment]
@HPaulJohnson Please see the sharable link you can send out with the promo kit.

https://drive.google.com/folderview?id=0B2qu3ExKWIlveVhwUzdZb1BJWFE&usp=sharing

**Comment by HPaulJohnson** [comment]
Thanks @lovegushwa. Moved relevant files into a publicly available dropbox too at http://mzl.la/WebmakerAssets (this is the link included in the promo kit).
