### ISSUE TITLE
Add me to Desk for support 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-launch#99]
Who has admin privileges?  cc @thisandagain @secretrobotron @simonwex

**Comment by thisandagain** [comment]
You already have access, but I have promoted you to an admin:
<img width="895" alt="screen shot 2015-08-19 at 3 01 36 pm" src="https://cloud.githubusercontent.com/assets/747641/9370182/27a0ac08-4683-11e5-844b-c967f8500b13.png">

Web Agent:
https://webmaker.desk.com/web/agent

Admin:
https://webmaker.desk.com/admin/dashboard
